WIP: added uplink JS & trying it calling from JS
I've started to create a Go type to expose methods that allow to perform
the uplink operations that we want but when I've realized that the
LoadAccess method didn't work, we started to take a look if calling the
UploadAndDonwloadData function would work calling from JS.

Hence, I've created a temporary UploadAndDonwload function that could be
called from JS to see if the problem was the JsUplink or it was
something else and wef found out that it's something else that happens
when calling these Go functions from JS and it provokes the following
error: "fatal error: all goroutines are asleep - deadlock!"